import styled from 'styled-components';

export const Footer = styled.footer`width: 100vw; margin-left: calc(50% - 50vw); padding: ${({ theme }) => theme.spacing[10]} max(24px, calc((100vw - ${({ theme }) => theme.layout.contentMax}) / 2)); color: ${({ theme }) => theme.colors.onBrand}; background: ${({ theme }) => theme.colors.nature[950]}; scroll-margin-top: ${({ theme }) => theme.layout.headerHeight}; @media (max-width: ${({ theme }) => theme.breakpoints.sm}) { padding-inline: ${({ theme }) => theme.spacing[8]}; }`;
export const CtaPanel = styled.div`padding: ${({ theme }) => theme.spacing[20]} ${({ theme }) => theme.spacing[12]}; border: 1px solid rgba(255,255,255,.15); border-radius: ${({ theme }) => theme.radii.xl}; background: ${({ theme }) => theme.colors.nature[700]}; text-align: center; @media (max-width: ${({ theme }) => theme.breakpoints.sm}) { padding: ${({ theme }) => theme.spacing[12]} ${({ theme }) => theme.spacing[5]}; }`;
export const Kicker = styled.p`margin: 0 0 ${({ theme }) => theme.spacing[4]}; color: ${({ theme }) => theme.colors.brand[200]}; font-size: ${({ theme }) => theme.typography.sizes.label}; font-weight: 900; letter-spacing: .12em; text-transform: uppercase;`;
export const Title = styled.h2`max-width: 850px; margin: 0 auto; font-size: ${({ theme }) => theme.typography.sizes.section}; line-height: 1.04; letter-spacing: -.04em;`;
export const Text = styled.p`max-width: 620px; margin: ${({ theme }) => theme.spacing[5]} auto 0; color: rgba(255,255,255,.68); font-size: ${({ theme }) => theme.typography.sizes.bodyLarge}; line-height: 1.65;`;
export const Action = styled.a`min-height: 56px; display: inline-flex; align-items: center; justify-content: center; gap: ${({ theme }) => theme.spacing[3]}; margin-top: ${({ theme }) => theme.spacing[8]}; padding: 0 ${({ theme }) => theme.spacing[6]}; border-radius: ${({ theme }) => theme.radii.round}; color: ${({ theme }) => theme.colors.brand[950]}; background: ${({ theme }) => theme.colors.surface}; font-weight: 900; text-decoration: none; transition: transform ${({ theme }) => theme.motion.normal} ${({ theme }) => theme.motion.ease}; &:hover { transform: translateY(-3px); }`;
export const Bottom = styled.div`min-height: 100px; display: grid; grid-template-columns: 1fr auto auto; align-items: center; gap: ${({ theme }) => theme.spacing[8]}; border-bottom: 1px solid rgba(255,255,255,.12); p { color: rgba(255,255,255,.52); font-size: 12px; } @media (max-width: ${({ theme }) => theme.breakpoints.sm}) { grid-template-columns: 1fr auto; padding-top: ${({ theme }) => theme.spacing[5]}; p { grid-column: 1 / -1; grid-row: 2; margin: 0 0 ${({ theme }) => theme.spacing[5]}; } }`;
export const Socials = styled.div`display: flex; gap: ${({ theme }) => theme.spacing[2]}; a { width: 44px; height: 44px; display: inline-flex; align-items: center; justify-content: center; border: 1px solid rgba(255,255,255,.2); border-radius: ${({ theme }) => theme.radii.round}; color: ${({ theme }) => theme.colors.onBrand}; text-decoration: none; }`;
export const Brand = styled.div`display: inline-flex; align-items: baseline; gap: ${({ theme }) => theme.spacing[2]}; strong { font-size: 22px; letter-spacing: -.055em; } span { color: ${({ theme }) => theme.colors.brand[300]}; font-size: 9px; }`;
export const Notice = styled.p`margin: ${({ theme }) => theme.spacing[5]} 0 0; color: rgba(255,255,255,.42); font-size: 11px; line-height: 1.5; text-align: center;`;
